# Generated by Django 4.2.7 on 2024-02-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amart', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('advice_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
