# Generated by Django 4.2.7 on 2024-02-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amart', '0003_advice_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('yield1', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Advice',
        ),
    ]
